@local_HostAddress = http://localhost:5022
@docker_HostAddress = http://localhost:8080

### Get all car brands - Local
GET {{local_HostAddress}}/api/MarcasAutos
Accept: application/json

###

### Get all car brands - Docker
GET {{docker_HostAddress}}/api/MarcasAutos
Accept: application/json

###