// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using car.Api.Data;

#nullable disable

namespace car.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("car.Api.Models.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Toyota",
                            Pais = "Japan"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ford",
                            Pais = "United States"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "BMW",
                            Pais = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Mercedes-Benz",
                            Pais = "Germany"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Honda",
                            Pais = "Japan"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Nissan",
                            Pais = "Japan"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Chevrolet",
                            Pais = "United States"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Hyundai",
                            Pais = "South Korea"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Kia",
                            Pais = "South Korea"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Volkswagen",
                            Pais = "Germany"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
